const CHORDS_AND_LYRICS_LINE = 'CHORDS_AND_LYRICS_LINE';
const ONLY_CHORDS_LINE = 'ONLY_CHORDS_LINE';
const LYRCIS_LINE = 'LYRCIS_LINE';

const CHORD_LINE_CHORD = 'CHORD_LINE_CHORD';
const CHORD_LINE_DIVIDER = 'CHORD_LINE_DIVIDER';

const DISPLAY_CHORDS = 'DISPLAY_CHORDS';
const DISPLAY_LYRICS = 'DISPLAY_LYRICS';
const DISPLAY_NASHVILLE = 'DISPLAY_NASHVILLE';
const DISPLAY_SOLFEGE = 'DISPLAY_SOLFEGE';
